name: Build SDL2 console apps (Switch)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-switch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: switch
            ext: nro
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Build ${{ matrix.platform }}
        run: make ${{ matrix.platform }}
      - uses: actions/upload-artifact@v4
        with:
          name: appstore.${{ matrix.ext }}
          path: /__w/hb-appstore/hb-appstore/appstore.${{ matrix.ext }}
